apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axonate.fullname" . }}-litellm-config
  labels:
    {{- include "axonate.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ if eq .Values.litellm.configMode "poc" }}{{ .Files.Get "files/litellm_config.yaml" | indent 4 }}{{ else }}{{ .Files.Get "files/litellm_config.prod.yaml" | indent 4 }}{{ end }}
